# Generated by Django 5.0.1 on 2025-02-15 20:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RunnerInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(default='', max_length=100, unique=True)),
                ('active_jobs', models.JSONField(default=list)),
                ('state', models.CharField(choices=[('idle', 'Idle'), ('busy', 'Busy'), ('offline', 'Offline')], default='offline', max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HardwareInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('runner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hardware', to='runner_manager.runnerinfo')),
            ],
        ),
    ]
