# Generated by Django 5.1.4 on 2025-02-23 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hardwareinfo',
            old_name='runner_id',
            new_name='runner',
        ),
        migrations.AddField(
            model_name='runnerinfo',
            name='last_contact',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='runnerinfo',
            name='token',
            field=models.CharField(default='', max_length=100),
        ),
    ]
