# Generated by Django 5.1.4 on 2025-04-12 20:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner_manager', '0002_rename_runner_id_hardwareinfo_runner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('system_name', models.CharField(max_length=100, null=True)),
                ('system_release', models.CharField(max_length=100, null=True)),
                ('system_version', models.CharField(max_length=100, null=True)),
                ('system_architecture', models.CharField(max_length=100, null=True)),
                ('cpu_model', models.CharField(max_length=100, null=True)),
                ('cpu_clock_speed_advertised', models.FloatField(null=True)),
                ('cpu_clock_speed_actual', models.FloatField(null=True)),
                ('cpu_logical_cores', models.IntegerField(null=True)),
                ('cpu_physical_cores', models.IntegerField(null=True)),
                ('cpu_cache_l1_size', models.IntegerField(null=True)),
                ('cpu_cache_l2_size', models.IntegerField(null=True)),
                ('cpu_cache_l3_size', models.IntegerField(null=True)),
                ('ram_size_total', models.IntegerField(null=True)),
                ('disk_size_total', models.IntegerField(null=True)),
                ('disk_size_available', models.IntegerField(null=True)),
                ('gpu_vendor', models.CharField(max_length=100, null=True)),
                ('gpu_model', models.CharField(max_length=100, null=True)),
                ('gpu_memory_size', models.IntegerField(null=True)),
                ('gpu_clock_speed', models.FloatField(null=True)),
                ('gpu_compute_units', models.IntegerField(null=True)),
                ('gpu_core_count', models.IntegerField(null=True)),
                ('gpu_driver_version', models.CharField(max_length=100, null=True)),
                ('runner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system', to='runner_manager.runnerinfo')),
            ],
        ),
        migrations.DeleteModel(
            name='HardwareInfo',
        ),
    ]
