# Generated by Django 5.0.14 on 2025-05-30 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("runner_manager", "0003_systeminfo_delete_hardwareinfo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="runnerinfo",
            name="active_jobs",
        ),
    ]
