# Generated by Django 5.0.14 on 2025-05-31 11:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("runner_manager", "0004_remove_runnerinfo_active_jobs"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RunnerInfo_1",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("token", models.CharField(default="", max_length=100)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("ID", "IDLE"),
                            ("BS", "BUSY"),
                            ("OF", "OFFLINE"),
                            ("UR", "UNREGISTERED"),
                        ],
                        default="UR",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_contact", models.DateTimeField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runner_1",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
