# Generated by Django 5.0.14 on 2025-09-23 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "runner_manager",
            "0006_runnerinfo_created_at_alter_runnerinfo_owner_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="runnerinfo",
            name="name",
            field=models.CharField(default="", max_length=100),
        ),
    ]
