# Generated by Django 5.0.14 on 2025-10-26 12:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AppInfo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identification number",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="job",
                        help_text="User provided name for the application",
                        max_length=100,
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        help_text="Full path to the application file", max_length=500
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("unknown", "unknown"),
                            ("python", "Python Script"),
                            ("linux_binary", "Linux Binary"),
                            ("windows_binary", "Windows Binary"),
                            ("shell", "Shell Script"),
                        ],
                        default="unknown",
                        help_text="Type of application program",
                        max_length=20,
                    ),
                ),
                (
                    "schema_path",
                    models.CharField(
                        blank=True,
                        help_text="Full path to the input schema file",
                        max_length=500,
                        null=True,
                    ),
                ),
            ],
        ),
    ]
