# Generated by Django 5.0.14 on 2025-06-04 13:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AppInfo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identification number",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="job",
                        help_text="User provided name for the job",
                        max_length=100,
                    ),
                ),
                ("file_path", models.FileField(upload_to="yaml_files/")),
            ],
        ),
    ]
