# Generated by Django 5.0.14 on 2025-11-01 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application_registry", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appinfo",
            name="default_cli_args",
            field=models.CharField(default="--input config.yml", max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="appinfo",
            name="executable_name",
            field=models.CharField(default="test_program.py", max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="appinfo",
            name="use_mpi",
            field=models.BooleanField(default=False),
        ),
    ]
