# Generated by Django 5.0.14 on 2025-06-06 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application_registry", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appinfo",
            name="type",
            field=models.CharField(
                choices=[
                    ("unknown", "unknown"),
                    ("python", "Python Script"),
                    ("linux_binary", "Linux Binary"),
                    ("windows_binary", "Windows Binary"),
                    ("shell", "Shell Script"),
                ],
                default="unknown",
                help_text="Type of application program",
                max_length=20,
            ),
        ),
    ]
