# Generated by Django 5.0.14 on 2025-06-07 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application_registry", "0002_appinfo_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appinfo",
            name="name",
            field=models.CharField(
                default="job",
                help_text="User provided name for the application",
                max_length=100,
            ),
        ),
    ]
