# Generated by Django 5.0.14 on 2025-11-02 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "application_registry",
            "0002_appinfo_default_cli_args_appinfo_executable_name_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="appinfo",
            old_name="type",
            new_name="application_type",
        ),
        migrations.AlterField(
            model_name="appinfo",
            name="default_cli_args",
            field=models.CharField(help_text="FIX ME", max_length=500),
        ),
        migrations.AlterField(
            model_name="appinfo",
            name="executable_name",
            field=models.CharField(help_text="FIX ME", max_length=500),
        ),
        migrations.AlterField(
            model_name="appinfo",
            name="use_mpi",
            field=models.BooleanField(default=False, help_text="FIX ME"),
        ),
    ]
