# Generated by Django 5.0.14 on 2025-11-02 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application_registry", "0003_rename_type_appinfo_application_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appinfo",
            name="name",
            field=models.CharField(
                help_text="User provided name for the application", max_length=100
            ),
        ),
    ]
