# Generated by Django 5.0.14 on 2025-06-07 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application_registry", "0003_alter_appinfo_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appinfo",
            name="file_path",
            field=models.CharField(
                help_text="Full path to the application file", max_length=500
            ),
        ),
    ]
