# Generated by Django 5.0.14 on 2025-09-23 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application_registry", "0004_alter_appinfo_file_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="appinfo",
            name="schema_path",
            field=models.CharField(
                blank=True,
                help_text="Full path to the input schema file",
                max_length=500,
                null=True,
            ),
        ),
    ]
