# Generated by Django 5.0.1 on 2024-02-07 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulation_manager", "0003_alter_simulation_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="simulation",
            name="name",
            field=models.CharField(default="Simulation", max_length=100),
        ),
    ]
