# Generated by Django 5.0.14 on 2025-06-01 08:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_manager", "0002_jobinfo_delete_job"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobinfo",
            name="priority",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
