# Generated by Django 5.1.4 on 2025-05-13 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulation_manager", "0002_simulation_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="simulation",
            name="status",
            field=models.CharField(
                choices=[
                    ("QD", "QUEUED"),
                    ("PR", "PREPARING"),
                    ("FR", "FETCHING_RESOURCES"),
                    ("ST", "STARTING"),
                    ("RN", "RUNNING"),
                    ("PD", "PAUSED"),
                    ("CU", "CLEANING_UP"),
                    ("UR", "UPLOADING_RESULTS"),
                    ("SD", "SUCCEEDED"),
                    ("FD", "FAILED"),
                    ("FS", "FAILED_RESOURCE_ERROR"),
                    ("FM", "FAILED_TERMINATED"),
                    ("FO", "FAILED_TIMEOUT"),
                ],
                default="QD",
                max_length=2,
            ),
        ),
    ]
