# Generated by Django 5.0.14 on 2025-06-04 13:46

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_manager", "0003_jobinfo_priority"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="jobinfo",
            name="command_line_args",
            field=models.JSONField(
                blank=True, default=list, help_text="List of command line arguments"
            ),
        ),
        migrations.AddField(
            model_name="jobinfo",
            name="executable",
            field=models.CharField(
                default="",
                help_text="Path to executable or command name",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="jobinfo",
            name="working_directory",
            field=models.CharField(
                blank=True,
                help_text="Working directory (on the remote runner) for job execution",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="jobinfo",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Creation date of the job."
            ),
        ),
        migrations.AlterField(
            model_name="jobinfo",
            name="created_by",
            field=models.ForeignKey(
                editable=False,
                help_text="User who created the job.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="job",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="jobinfo",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Unique job identification number",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="jobinfo",
            name="name",
            field=models.CharField(
                default="job",
                help_text="User provided name for the job",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="jobinfo",
            name="priority",
            field=models.IntegerField(
                default=0,
                help_text="Queueing priority, will determine position in remote runner's queue.",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="jobinfo",
            name="status",
            field=models.CharField(
                choices=[
                    ("QD", "QUEUED"),
                    ("PR", "PREPARING"),
                    ("FR", "FETCHING_RESOURCES"),
                    ("ST", "STARTING"),
                    ("RN", "RUNNING"),
                    ("PD", "PAUSED"),
                    ("CU", "CLEANING_UP"),
                    ("UR", "UPLOADING_RESULTS"),
                    ("SD", "SUCCEEDED"),
                    ("FD", "FAILED"),
                    ("FS", "FAILED_RESOURCE_ERROR"),
                    ("FM", "FAILED_TERMINATED"),
                    ("FO", "FAILED_TIMEOUT"),
                    ("FE", "FAILED_RUNNER_EXCEPTION"),
                ],
                default="QD",
                help_text="Current status of the job.",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="jobinfo",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, help_text="Date of last update."),
        ),
    ]
