# Generated by Django 5.0.14 on 2025-06-04 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application_registry", "0001_initial"),
        ("job_manager", "0004_jobinfo_command_line_args_jobinfo_executable_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobinfo",
            name="application_id",
            field=models.ForeignKey(
                help_text="The application id this job will execute",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="application_registry.appinfo",
            ),
        ),
    ]
