# Generated by Django 5.0.14 on 2025-06-07 07:26

import django.db.models.deletion
import job_manager.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_manager", "0005_jobinfo_application_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobinfo",
            name="yaml_file",
        ),
        migrations.AddField(
            model_name="jobinfo",
            name="local_working_directory",
            field=models.CharField(
                blank=True,
                default=models.CharField(
                    blank=True,
                    help_text="Working directory (on the remote runner) for job execution",
                    max_length=500,
                    null=True,
                ),
                help_text="Working directory (used by the server) for job execution",
                max_length=500,
            ),
        ),
        migrations.CreateModel(
            name="JobResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("IN", "INPUT"),
                            ("OUT", "OUTPUT"),
                            ("CFG", "CONFIG"),
                            ("LOG", "LOG"),
                            ("TMP", "TEMPORARY"),
                            ("RES", "RESULT"),
                        ],
                        default="IN",
                        help_text="Type of resource (input, output, config, etc.)",
                        max_length=3,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="The actual file/resource",
                        upload_to=job_manager.models.job_resource_upload_path,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Optional description of the resource",
                        max_length=200,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the resource was created/uploaded",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who created/uploaded this resource (user or system)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job_id",
                    models.ForeignKey(
                        help_text="Job this resource belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="job_manager.jobinfo",
                    ),
                ),
            ],
            options={
                "ordering": ["resource_type", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["job_id", "resource_type"],
                        name="job_manager_job_id__d9067e_idx",
                    )
                ],
            },
        ),
    ]
