# Generated by Django 5.0.14 on 2025-06-07 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("job_manager", "0006_remove_jobinfo_yaml_file_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="jobresource",
            old_name="job_id",
            new_name="job",
        ),
        migrations.RenameIndex(
            model_name="jobresource",
            new_name="job_manager_job_id_65e265_idx",
            old_name="job_manager_job_id__d9067e_idx",
        ),
    ]
