# Generated by Django 5.0.14 on 2025-06-07 08:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_manager", "0007_rename_job_id_jobresource_job_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="jobresource",
            name="job_manager_job_id_65e265_idx",
        ),
        migrations.AlterField(
            model_name="jobinfo",
            name="local_working_directory",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Local working directory path for this job",
                max_length=500,
            ),
        ),
        migrations.AddIndex(
            model_name="jobresource",
            index=models.Index(
                fields=["job", "resource_type"], name="job_manager_job_id_65e265_idx"
            ),
        ),
    ]
