# Generated by Django 5.0.14 on 2025-06-07 09:05

import job_manager.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "job_manager",
            "0008_remove_jobresource_job_manager_job_id_65e265_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobresource",
            name="file",
            field=models.FileField(
                help_text="The actual file/resource",
                storage=job_manager.models.PreserveFilenameStorage(),
                upload_to=job_manager.models.job_resource_upload_path,
            ),
        ),
        migrations.AddConstraint(
            model_name="jobresource",
            constraint=models.UniqueConstraint(
                fields=("job", "file"), name="unique_job_file"
            ),
        ),
    ]
