# Generated by Django 5.0.14 on 2025-06-14 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_manager", "0009_alter_jobresource_file_jobresource_unique_job_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobinfo",
            name="exit_code",
            field=models.IntegerField(
                blank=True,
                help_text="The exit code of the application which was executed.",
                null=True,
            ),
        ),
    ]
