# Generated by Django 5.0.14 on 2025-06-16 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_manager", "0010_jobinfo_exit_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobresource",
            name="original_file_path",
            field=models.CharField(
                blank=True,
                help_text="Original file path where this resource was created (optional)",
                max_length=500,
            ),
        ),
    ]
