# Generated by Django 5.0.14 on 2025-09-28 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application_registry", "0005_appinfo_schema_path"),
        ("job_manager", "0011_jobresource_original_file_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobinfo",
            name="application_id",
            field=models.ForeignKey(
                default="7d215e75ddef4b4fb6fc4d27a9cdffd8",
                help_text="The application id this job will execute",
                on_delete=django.db.models.deletion.CASCADE,
                to="application_registry.appinfo",
            ),
            preserve_default=False,
        ),
    ]
