# Generated by Django 5.0.14 on 2025-10-03 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_manager", "0012_alter_jobinfo_application_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobinfo",
            name="status",
            field=models.CharField(
                choices=[
                    ("UI", "UPLOADING_INPUT_RESOURCES"),
                    ("QD", "QUEUED"),
                    ("PR", "PREPARING"),
                    ("FR", "FETCHING_RESOURCES"),
                    ("ST", "STARTING"),
                    ("RN", "RUNNING"),
                    ("PD", "PAUSED"),
                    ("CU", "CLEANING_UP"),
                    ("UR", "UPLOADING_RESULTS"),
                    ("SD", "SUCCEEDED"),
                    ("FD", "FAILED"),
                    ("FS", "FAILED_RESOURCE_ERROR"),
                    ("FM", "FAILED_TERMINATED"),
                    ("FO", "FAILED_TIMEOUT"),
                    ("FE", "FAILED_RUNNER_EXCEPTION"),
                ],
                default="QD",
                help_text="Current status of the job.",
                max_length=2,
            ),
        ),
    ]
