# Generated by Django 5.0.14 on 2025-10-06 16:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_manager", "0013_alter_jobinfo_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobresource",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Unique resource identification number",
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
