name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches: [ main ]
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run tests
      run: |
        python manage.py test
        
    - name: Generate deployment package
      run: |
        zip -r deploy.zip . -x "*.git*"

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-north-1

    - name: Set RDS Password in EB Environment
      run: |
        aws elasticbeanstalk update-environment \
          --environment-name "fyn-api-env" \
          --option-settings Namespace=aws:elasticbeanstalk:application:environment,OptionName=RDS_PASSWORD,Value=${{ secrets.RDS_PASSWORD }}

    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v21
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: "fyn-api"   
        environment_name: "fyn-api-env"   
        region: "eu-north-1"
        version_label: "v-${{ github.sha }}"
        deployment_package: deploy.zip
        use_existing_version_if_available: true

